name = "example_flappy"
version = "0.1.0"
defaultTargets = ["ExampleFlappyApp"]

[leanOptions]
autoImplicit = false

[[require]]
name = "sdl_bindings"
path = "../sdl-bindings"

[[require]]
name = "flappy"
git = "https://github.com/paulcadman/flappy.git"
rev = "ae49fe7c1a2af64cd38ccc7ac26b6f4ea9d58639"

[[lean_lib]]
name = "ExampleFlappyApp"
srcDir = "lean"
roots = ["ExampleFlappy"]
defaultFacets = ["static"]
