include App.mk

APP_BUILD_DIR ?= $(ROOT_DIR)/build/example-bus-times-sim

include ../app-common/Makefile.sim

$(APP_OBJ_DIR)/HttpBridge.o: $(APP_NATIVE_DIR)/HttpBridge.m
	mkdir -p $(APP_OBJ_DIR)
	xcrun --sdk $(IOS_SDK) clang \
	  -target $(IOS_TARGET) \
	  -isysroot $(IOS_SDK_PATH) \
	  $(APP_MIN_VERSION_FLAG) \
	  -I$(RUNTIME_BUILD_DIR)/include \
	  -I$(LEAN_SRC_DIR)/stage0/src/include \
	  -I$(LEAN_SRC_DIR)/src/include \
	  $(APP_PROJECT_CFLAGS) \
	  -fobjc-arc \
	  -c $< \
	  -o $@
