IOS_DEPLOYMENT_TARGET ?= 16.0
IOS_SDK ?= iphoneos
IOS_TARGET ?= arm64-apple-ios$(IOS_DEPLOYMENT_TARGET)
APP_MIN_VERSION_FLAG ?= -miphoneos-version-min=$(IOS_DEPLOYMENT_TARGET)

include Makefile.common

.PHONY: device-app

device-app: app
